steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "functions",
        "deploy",
        "crawl",
        "--source=./src",
        "--trigger-topic=univNews_topic",
        "--runtime",
        "python37",
        "--entry-point",
        "crawl",
        "--region",
        "asia-northeast1",
      ]
